-- Akira アキラ — colorscheme
-- lua/plugins/colorscheme.lua  (akira-lazyvim repo)
--
-- Uses tokyonight as the base and overrides its palette
--
-- The palette is generated by the akira repo (scripts/theme.sh)
-- and installed to ~/.akira/theme/palette.lua. It is deliberately
-- NOT vendored here: this file must stay the only consumer, never
-- a second copy of the values.
--
-- When the palette is missing — a standalone clone, or akira not
-- installed yet — tokyonight loads with its own defaults. That is
-- visibly different from Akira, which is the point: a silent
-- fallback carrying stale colors would be worse than an obvious one.

local PALETTE = vim.fn.expand("~/.akira/theme/palette.lua")

local function load_palette()
  local uv = vim.uv or vim.loop
  if not uv.fs_stat(PALETTE) then
    return nil, "not found"
  end

  local ok, result = pcall(dofile, PALETTE)
  if not ok then
    return nil, tostring(result)
  end
  if type(result) ~= "table" or result.bg == nil then
    return nil, "malformed (expected a table with color keys)"
  end

  return result
end

local akira, err = load_palette()

if not akira then
  vim.schedule(function()
    vim.notify(
      ("Akira palette unavailable (%s).\nFalling back to stock tokyonight.\nRun scripts/theme.sh in the akira repo, then config.sh."):format(
        err
      ),
      vim.log.levels.WARN,
      { title = "Akira" }
    )
  end)
end

---@type table
local opts = {
  style = "night",
  transparent = false,
  terminal_colors = true,
  styles = {
    comments = { italic = true },
    keywords = { italic = false },
    functions = {},
    variables = {},
    sidebars = "dark",
    floats = "dark",
  },
}

-- Only override when a real palette is present.
if akira then
  opts.on_colors = function(c)
    -- Surfaces
    c.bg = akira.bg
    c.bg_dark = akira.bg_dark
    c.bg_float = akira.bg_dark
    c.bg_sidebar = akira.bg_dark
    c.bg_statusline = akira.bg_dark
    c.bg_popup = akira.bg_dark
    c.bg_highlight = akira.highlight
    c.bg_visual = akira.highlight

    -- Text
    c.fg = akira.fg
    c.fg_dark = akira.fg_dark
    c.fg_sidebar = akira.fg_dark
    c.comment = akira.comment

    -- Borders
    c.border = akira.border
    c.border_highlight = akira.border_hi

    -- Accents
    c.red = akira.red
    c.orange = akira.orange
    c.yellow = akira.yellow
    c.green = akira.green
    c.teal = akira.teal
    c.cyan = akira.cyan
    c.blue = akira.blue
    c.magenta = akira.magenta
  end

  opts.on_highlights = function(hl, c)
    -- Window borders, matching the hyprland border tokens
    hl.WinSeparator = { fg = c.border, bold = true }
    hl.FloatBorder = { fg = c.border_highlight, bg = c.bg_float }
    hl.NormalFloat = { fg = c.fg, bg = c.bg_float }

    -- Line numbers
    hl.LineNr = { fg = c.border }
    hl.CursorLineNr = { fg = c.blue, bold = true }

    -- File explorer on the darker surface
    hl.NeoTreeNormal = { fg = c.fg_sidebar, bg = c.bg_dark }
    hl.NeoTreeNormalNC = { fg = c.fg_sidebar, bg = c.bg_dark }
    hl.NeoTreeWinSeparator = { fg = c.bg_dark, bg = c.bg_dark }

    -- Pickers
    hl.TelescopeBorder = { fg = c.border, bg = c.bg_dark }
    hl.TelescopeNormal = { fg = c.fg, bg = c.bg_dark }
    hl.TelescopeTitle = { fg = c.magenta, bold = true }
    hl.TelescopeSelection = { bg = c.bg_highlight, bold = true }

    hl.WhichKeyBorder = { fg = c.border, bg = c.bg_dark }
  end
end

return {
  {
    "folke/tokyonight.nvim",
    lazy = false,
    priority = 1000,
    opts = opts,
  },

  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "tokyonight",
    },
  },
}
